stages:
  processed_data:
    cmd: python src/model/processed_data.py
    deps:
    - src/model/processed_data.py
    - src/data/raw/farms_data.csv
    outs:
    - src/data/processed/processed_farms_data.csv

  train:
    cmd: python src/model/train.py
    deps:
    - src/model/train.py
    - src/data/processed/processed_farms_data.csv
    outs:
    - outputs/by_region.png
    metrics:
    - outputs/metrics.json:
        cache: false



