name: farmers
on: [push]
jobs:
  train-and-report:
    runs-on: ubuntu-latest
    container: docker://ghcr.io/iterative/cml:0-dvc2-base1
    steps:
      - uses: actions/checkout@v3
      - name: Train model
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
	        git config --global --add safe.directory /__w/track_ml_model/track_ml_model
          dvc repro # her dosyanın ciktisini yeniden üretecek
          git fetch --prune
          dvc outpust/metrics diff --show-md master > report.md

          # add figure to report.md
          echo "## Validation restulr by region"
          echo '![](./by_region.png )' >> report.md
          cml comment create report.md